name = "progress-websocket-durable-object"
main = "src/index.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Observability for Durable Objects
[observability]
enabled = true
head_sampling_rate = 1.0  # Sample 100% of requests for debugging

# Log all WebSocket events and RPC calls
[vars]
LOG_LEVEL = "DEBUG"

# Durable Object classes defined in this worker
[[durable_objects.bindings]]
name = "PROGRESS_WEBSOCKET_DO"
class_name = "ProgressWebSocketDO"
script_name = "progress-websocket-durable-object"

[[migrations]]
tag = "v1"
new_classes = ["ProgressWebSocketDO"]
