name = "isbndb-biography-worker-production"
main = "src/index.js"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]

# Define the class that will handle RPC calls
entrypoint = "ISBNdbWorker"

limits = { cpu_ms = 30000 }

[observability]
enabled = true

[[analytics_engine_datasets]]
binding = "ISBNDB_ANALYTICS"
dataset = "isbndb_worker_performance"

[vars]
ENABLE_PERFORMANCE_LOGGING = "true"
LOG_LEVEL = "INFO"
STRUCTURED_LOGGING = "true"
ENABLE_RATE_LIMIT_TRACKING = "true"

[[secrets_store_secrets]]
binding = "ISBNDB_API_KEY"
store_id = "b0562ac16fde468c8af12717a6c88400"
secret_name = "ISBNDB_API_KEY"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "b9cade63b6db48fd80c109a013f38fdb"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "books-cache"