name = "personal-library-cache-warmer"
main = "src/index.js"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]

# PAID TIER OPTIMIZATION: Maximum CPU and memory allocation
[limits]
cpu_ms = 30000        # Max CPU time per request
memory_mb = 256       # Increased memory for concurrent processing

# Enable advanced observability for performance monitoring
[placement]
mode = "smart"         # Smart placement for optimal performance

[observability]
enabled = true

# Performance monitoring configuration
[[analytics_engine_datasets]]
binding = "PERFORMANCE_METRICS"
dataset = "cache_warmer_performance"

[[secrets_store_secrets]]
binding = "ISBNDB_API_KEY"
store_id = "b0562ac16fde468c8af12717a6c88400"
secret_name = "ISBNDB_API_KEY"

[[services]]
binding = "BOOKS_API_PROXY"
service = "books-api-proxy"

[[services]]
binding = "ISBNDB_WORKER"
service = "isbndb-biography-worker-production"

[[kv_namespaces]]
binding = "CACHE"
id = "b9cade63b6db48fd80c109a013f38fdb"

[[r2_buckets]]
binding = "LIBRARY_DATA"
bucket_name = "personal-library-data"

# AGGRESSIVE CRON SCHEDULE - Maximizes ISBNdb API quota utilization
[triggers]
crons = [
    "*/5 * * * *",   # Every 5 minutes - High frequency processing (15 authors)
    "*/15 * * * *",  # Every 15 minutes - Regular processing (25 authors)
    "0 */4 * * *",   # Every 4 hours - Large batch processing (50 authors)
    "0 2 * * *"      # Daily - Cache verification and repair
]