# Minimal Working Cache Warmer Configuration
name = "personal-library-cache-warmer"
main = "src/index.js"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]

# Paid Plan CPU Limits
limits = { cpu_ms = 30000 }

# Basic observability
[observability]
enabled = true

# Service bindings for worker-to-worker communication
[[services]]
binding = "BOOKS_API_PROXY"
service = "books-api-proxy"

[[services]]
binding = "ISBNDB_WORKER"
service = "isbndb-biography-worker-production"

# KV Storage for warming progress and results
[[kv_namespaces]]
binding = "WARMING_CACHE"
id = "69949ba5a5b44214b7a2e40c1b687c35"

# R2 Storage for CSV uploads and processed results
[[r2_buckets]]
binding = "LIBRARY_DATA"
bucket_name = "personal-library-data"

# Secrets management
secrets_store_secrets = [
  { binding = "ISBNDB_API_KEY", store_id = "b0562ac16fde468c8af12717a6c88400", secret_name = "ISBNDB_API_KEY" },
  { binding = "GOOGLE_BOOKS_HARDOOOE", store_id = "b0562ac16fde468c8af12717a6c88400", secret_name = "Google_books_hardoooe" },
  { binding = "GOOGLE_BOOKS_IOSKEY", store_id = "b0562ac16fde468c8af12717a6c88400", secret_name = "Google_books_ioskey" },
  { binding = "ISBN_SEARCH_KEY", store_id = "b0562ac16fde468c8af12717a6c88400", secret_name = "ISBN_search_key" }
]

# Cron triggers for automated warming
[triggers]
crons = [
  "0 6 * * 1",   # Weekly: 6 AM UTC Monday - Full library re-warming
  "0 12 * * *"   # Daily: 12 PM UTC - New additions check
]