name = "personal-library-cache-warmer"
main = "src/index.js"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]

limits = { cpu_ms = 30000 }

[observability]
enabled = true

[[secrets_store_secrets]]
binding = "ISBNDB_API_KEY"
store_id = "b0562ac16fde468c8af12717a6c88400"
secret_name = "ISBNDB_API_KEY"

[[services]]
binding = "BOOKS_API_PROXY"
service = "books-api-proxy"

[[services]]
binding = "ISBNDB_WORKER"
service = "isbndb-biography-worker-production"

[[kv_namespaces]]
binding = "CACHE"
id = "b9cade63b6db48fd80c109a013f38fdb"

[[r2_buckets]]
binding = "LIBRARY_DATA"
bucket_name = "personal-library-data"

[triggers]
crons = [
    "*/15 * * * *",
    "0 2 * * *"
]