name = "openlibrary-search-worker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Define the class that will handle RPC calls
entrypoint = "OpenLibraryWorker"

main = "src/index.js"

[env.production]
kv_namespaces = [
  { binding = "KV_CACHE", id = "b9cade63b6db48fd80c109a013f38fdb" }
]

[observability]
enabled = true

[[analytics_engine_datasets]]
binding = "OPENLIBRARY_ANALYTICS"
dataset = "openlibrary_performance"

[vars]
WORKER_NAME = "openlibrary-search-worker"
VERSION = "1.0.0"

[env.production.vars]
WORKER_NAME = "openlibrary-search-worker"
VERSION = "1.0.0"
ENABLE_PERFORMANCE_LOGGING = "true"
LOG_LEVEL = "INFO"
STRUCTURED_LOGGING = "true"