# OpenLibrary Search Worker Configuration
name = "openlibrary-search-worker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Main worker file
main = "src/index.js"

# Worker settings optimized for OpenLibrary API calls
[env.production]
kv_namespaces = [
  { binding = "KV_CACHE", id = "b9cade63b6db48fd80c109a013f38fdb" }
]

# Service binding for RPC calls from books-api-proxy
# This worker will be called by books-api-proxy

# Development environment
[env.staging]
kv_namespaces = [
  { binding = "KV_CACHE", id = "8e05b3b27f404b7789cd9a00d19208bc" }
]

# Memory and CPU optimizations for API processing
# OpenLibrary API is generally fast, so standard limits should suffice

# Environment variables (if needed)
[vars]
WORKER_NAME = "openlibrary-search-worker"
VERSION = "1.0.0"

[env.production.vars]
WORKER_NAME = "openlibrary-search-worker"
VERSION = "1.0.0"