name = "google-books-worker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Define the class that will handle RPC calls
entrypoint = "GoogleBooksWorker"

main = "src/index.js"

[env.production]
kv_namespaces = [
  { binding = "KV_CACHE", id = "b9cade63b6db48fd80c109a013f38fdb" }
]

[observability]
enabled = true

[[analytics_engine_datasets]]
binding = "GOOGLE_BOOKS_ANALYTICS"
dataset = "google_books_performance"

# Secrets management using secrets store
[[secrets_store_secrets]]
binding = "GOOGLE_BOOKS_API_KEY"
store_id = "b0562ac16fde468c8af12717a6c88400"
secret_name = "Google_books_hardoooe"

[vars]
WORKER_NAME = "google-books-worker"
VERSION = "1.0.0"

[env.production.vars]
WORKER_NAME = "google-books-worker"
VERSION = "1.0.0"
ENABLE_PERFORMANCE_LOGGING = "true"
LOG_LEVEL = "INFO"
STRUCTURED_LOGGING = "true"